name: user_data
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get_it: ^7.2.0
  injectable: ^2.1.1
  flutter_bloc: ^8.1.2
  go_router: ^6.5.6
  floor: ^1.4.1
  sqflite: ^2.2.6
  file_picker: ^5.2.9
  path_provider: ^2.0.14
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  injectable_generator: ^2.1.5
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  floor_generator: ^1.4.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true